version: '3.8'

services:
    database:
      container_name: database
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: mysql
        MYSQL_DATABASE: db
        MYSQL_USER: nextjs
        MYSQL_PASSWORD: nextjs
      ports:
        - '3306:3306'
      volumes:
        - ./mysql:/var/lib/mysql